-- ============================================================
-- FOODY – Community Wochenpläne mit echten Rezepten
-- Verwendet das korrekte MealPlanEntry-Format:
--   { id, dayIndex (0=Mo..6=So), slot (breakfast/lunch/dinner), recipe: { FoodRecipe } }
-- ============================================================

DO $outer$
DECLARE
  v_user1  uuid;
  v_user2  uuid;
  v_user3  uuid;
  v_plan1  jsonb;
  v_plan2  jsonb;
  v_plan3  jsonb;
BEGIN
  SELECT id INTO v_user1 FROM auth.users ORDER BY created_at LIMIT 1;
  SELECT id INTO v_user2 FROM auth.users ORDER BY created_at OFFSET 1 LIMIT 1;
  SELECT id INTO v_user3 FROM auth.users ORDER BY created_at OFFSET 2 LIMIT 1;

  IF v_user2 IS NULL THEN v_user2 := v_user1; END IF;
  IF v_user3 IS NULL THEN v_user3 := v_user1; END IF;

  -- Alte Test-Pläne ohne Mahlzeiten entfernen
  DELETE FROM public.community_meal_plans
  WHERE title IN (
    'Mediterrane Genusswoche 🌊','Vegane Power-Woche 🌱',
    'Meal-Prep Woche für Berufstätige ⚡','Mediterrane Woche 🌊',
    'Vegane Wochenchallenge','Schnell & Gesund'
  );

  -- ──────────────────────────────────────────────────────────
  -- JSON-Variablen mit Dollar-Quoting zuweisen
  -- (kein SQL-Parsing innerhalb $json$...$json$)
  -- ──────────────────────────────────────────────────────────

  v_plan1 := $json1$[
    {"id":"mp1-mo-b","dayIndex":0,"slot":"breakfast","recipe":{"id":"mp1-r1","title":"Avocado Toast mit Ei","description":"Knuspriger Toast mit cremiger Avocado und Spiegelei","cookingTimeMinutes":10,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Vollkorntoast","amount":"2 Scheiben"},{"name":"Avocado","amount":"1 Stück"},{"name":"Eier","amount":"2 Stück"},{"name":"Zitronensaft","amount":"1 TL"},{"name":"Salz und Pfeffer","amount":"nach Geschmack"}],"steps":["Toast rösten","Avocado zerdrücken und würzen","Eier braten","Auf Toast anrichten"]}},
    {"id":"mp1-mo-l","dayIndex":0,"slot":"lunch","recipe":{"id":"mp1-r2","title":"Griechischer Salat","description":"Klassischer Salat mit Feta, Oliven und frischem Gemüse","cookingTimeMinutes":15,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Tomaten","amount":"3 Stück"},{"name":"Gurke","amount":"1 Stück"},{"name":"Rote Zwiebel","amount":"1 Stück"},{"name":"Feta","amount":"150 g"},{"name":"Oliven","amount":"100 g"},{"name":"Olivenöl","amount":"3 EL"},{"name":"Oregano","amount":"1 TL"}],"steps":["Gemüse würfeln","Feta zerbröseln","Alles mischen","Mit Öl und Oregano würzen"]}},
    {"id":"mp1-mo-d","dayIndex":0,"slot":"dinner","recipe":{"id":"mp1-r3","title":"Spaghetti Carbonara","description":"Das Original aus Rom – cremig ohne Sahne","cookingTimeMinutes":25,"difficulty":"Mittel","servings":2,"ingredients":[{"name":"Spaghetti","amount":"200 g"},{"name":"Guanciale","amount":"100 g"},{"name":"Pecorino Romano","amount":"60 g"},{"name":"Eier","amount":"4 Stück"},{"name":"Schwarzer Pfeffer","amount":"reichlich"}],"steps":["Nudeln kochen","Guanciale braten","Ei-Käse-Mix anrühren","Alles vermengen","Sofort servieren"]}},
    {"id":"mp1-di-b","dayIndex":1,"slot":"breakfast","recipe":{"id":"mp1-r4","title":"Shakshuka","description":"Eier pochiert in würziger Tomatensauce","cookingTimeMinutes":20,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Eier","amount":"4 Stück"},{"name":"Dosentomaten","amount":"400 g"},{"name":"Paprika","amount":"1 Stück"},{"name":"Zwiebel","amount":"1 Stück"},{"name":"Knoblauch","amount":"2 Zehen"},{"name":"Kreuzkümmel","amount":"1 TL"},{"name":"Paprikapulver","amount":"1 TL"}],"steps":["Zwiebeln und Paprika anbraten","Tomaten hinzufügen","Würzen","Eier einschlagen","Zugedeckt garen"]}},
    {"id":"mp1-di-l","dayIndex":1,"slot":"lunch","recipe":{"id":"mp1-r5","title":"Linsensuppe","description":"Herzhafte rote Linsensuppe mit Gemüse","cookingTimeMinutes":30,"difficulty":"Einfach","servings":4,"ingredients":[{"name":"Rote Linsen","amount":"200 g"},{"name":"Karotten","amount":"2 Stück"},{"name":"Zwiebel","amount":"1 Stück"},{"name":"Knoblauch","amount":"2 Zehen"},{"name":"Gemüsebrühe","amount":"1 Liter"},{"name":"Kreuzkümmel","amount":"1 TL"},{"name":"Zitronensaft","amount":"2 EL"}],"steps":["Gemüse schneiden","Anbraten","Linsen und Brühe hinzufügen","20 Min. kochen","Pürieren und würzen"]}},
    {"id":"mp1-di-d","dayIndex":1,"slot":"dinner","recipe":{"id":"mp1-r6","title":"Lachs mit Ofengemüse","description":"Saftige Lachsfilets mit Rosmarinkartoffeln","cookingTimeMinutes":35,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Lachsfilet","amount":"2 Filets"},{"name":"Kartoffeln","amount":"400 g"},{"name":"Zucchini","amount":"1 Stück"},{"name":"Paprika","amount":"1 Stück"},{"name":"Olivenöl","amount":"3 EL"},{"name":"Rosmarin","amount":"2 Zweige"},{"name":"Zitrone","amount":"1 Stück"}],"steps":["Ofen auf 200 Grad","Gemüse würfeln und würzen","20 Min. backen","Lachs hinzufügen","Weitere 15 Min. garen"]}},
    {"id":"mp1-mi-b","dayIndex":2,"slot":"breakfast","recipe":{"id":"mp1-r1b","title":"Avocado Toast","description":"Knuspriger Toast mit cremiger Avocado","cookingTimeMinutes":10,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Toast","amount":"2 Scheiben"},{"name":"Avocado","amount":"1 Stück"},{"name":"Ei","amount":"1 Stück"}],"steps":["Toast rösten","Avocado drauf","Ei braten"]}},
    {"id":"mp1-mi-l","dayIndex":2,"slot":"lunch","recipe":{"id":"mp1-r5b","title":"Linsensuppe","description":"Herzhafte rote Linsensuppe","cookingTimeMinutes":30,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Linsen","amount":"150 g"},{"name":"Gemüse","amount":"nach Wahl"},{"name":"Brühe","amount":"800 ml"}],"steps":["Kochen","Würzen","Servieren"]}},
    {"id":"mp1-mi-d","dayIndex":2,"slot":"dinner","recipe":{"id":"mp1-r7","title":"Pizza Margherita","description":"Klassische Pizza mit Tomaten und Mozzarella","cookingTimeMinutes":40,"difficulty":"Mittel","servings":2,"ingredients":[{"name":"Pizzateig","amount":"300 g"},{"name":"Tomatensauce","amount":"150 ml"},{"name":"Mozzarella","amount":"200 g"},{"name":"Basilikum","amount":"1 Handvoll"},{"name":"Olivenöl","amount":"2 EL"}],"steps":["Teig ausrollen","Sauce verteilen","Käse drauf","25 Min. bei 220 Grad backen"]}},
    {"id":"mp1-do-b","dayIndex":3,"slot":"breakfast","recipe":{"id":"mp1-r4b","title":"Shakshuka","description":"Eier in Tomatensauce","cookingTimeMinutes":20,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Eier","amount":"3 Stück"},{"name":"Tomaten","amount":"400 g"},{"name":"Gewürze","amount":"nach Geschmack"}],"steps":["Sauce kochen","Eier einschlagen","Garen"]}},
    {"id":"mp1-do-l","dayIndex":3,"slot":"lunch","recipe":{"id":"mp1-r2b","title":"Griechischer Salat","description":"Frischer Sommersalat","cookingTimeMinutes":10,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Tomaten","amount":"2 Stück"},{"name":"Feta","amount":"100 g"},{"name":"Gurke","amount":"1 Stück"}],"steps":["Schneiden","Würzen","Genießen"]}},
    {"id":"mp1-do-d","dayIndex":3,"slot":"dinner","recipe":{"id":"mp1-r8","title":"Hähnchen Tikka Masala","description":"Zartes Hähnchen in aromatischer Tomatensauce","cookingTimeMinutes":45,"difficulty":"Mittel","servings":4,"ingredients":[{"name":"Hähnchenbrust","amount":"600 g"},{"name":"Joghurt","amount":"200 ml"},{"name":"Dosentomaten","amount":"400 g"},{"name":"Sahne","amount":"100 ml"},{"name":"Tikka Masala Paste","amount":"3 EL"},{"name":"Zwiebeln","amount":"2 Stück"},{"name":"Knoblauch","amount":"3 Zehen"}],"steps":["Hähnchen marinieren","Anbraten","Sauce zubereiten","30 Min. köcheln","Mit Reis servieren"]}},
    {"id":"mp1-fr-b","dayIndex":4,"slot":"breakfast","recipe":{"id":"mp1-r1c","title":"Avocado Toast","description":"Einfaches Frühstück","cookingTimeMinutes":10,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Toast","amount":"2 Scheiben"},{"name":"Avocado","amount":"1 Stück"}],"steps":["Toast rösten","Avocado drauf"]}},
    {"id":"mp1-fr-d","dayIndex":4,"slot":"dinner","recipe":{"id":"mp1-r9","title":"Meeresfrüchte Risotto","description":"Cremiges Risotto mit Garnelen und Muscheln","cookingTimeMinutes":40,"difficulty":"Schwer","servings":2,"ingredients":[{"name":"Risotto-Reis","amount":"300 g"},{"name":"Garnelen","amount":"200 g"},{"name":"Miesmuscheln","amount":"300 g"},{"name":"Weißwein","amount":"150 ml"},{"name":"Fischbrühe","amount":"800 ml"},{"name":"Parmesan","amount":"60 g"},{"name":"Butter","amount":"50 g"}],"steps":["Schalotten anbraten","Reis rösten","Mit Wein ablöschen","Brühe schrittweise hinzufügen","Meeresfrüchte dazu","Mit Butter und Parmesan verfeinern"]}},
    {"id":"mp1-sa-b","dayIndex":5,"slot":"breakfast","recipe":{"id":"mp1-r4c","title":"Shakshuka","description":"Würziges Frühstück","cookingTimeMinutes":20,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Eier","amount":"4 Stück"},{"name":"Tomaten","amount":"400 g"}],"steps":["Sauce kochen","Eier garen"]}},
    {"id":"mp1-sa-d","dayIndex":5,"slot":"dinner","recipe":{"id":"mp1-r10","title":"Tiramisu","description":"Das klassische Dessert aus Venetien","cookingTimeMinutes":30,"difficulty":"Mittel","servings":6,"ingredients":[{"name":"Mascarpone","amount":"500 g"},{"name":"Eier","amount":"4 Stück"},{"name":"Zucker","amount":"100 g"},{"name":"Espresso","amount":"300 ml"},{"name":"Löffelbiskuits","amount":"200 g"},{"name":"Kakao","amount":"zum Bestäuben"}],"steps":["Eigelb mit Zucker schlagen","Mascarpone unterrühren","Eiweiß steif schlagen","Unterziehen","Biskuits tauchen","Schichten und kühlen"]}},
    {"id":"mp1-so-b","dayIndex":6,"slot":"breakfast","recipe":{"id":"mp1-r11","title":"Pancakes mit Beeren","description":"Fluffige Pancakes mit frischen Beeren","cookingTimeMinutes":20,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Mehl","amount":"150 g"},{"name":"Milch","amount":"200 ml"},{"name":"Ei","amount":"1 Stück"},{"name":"Backpulver","amount":"1 TL"},{"name":"Beeren","amount":"200 g"},{"name":"Ahornsirup","amount":"nach Geschmack"}],"steps":["Teig mischen","Pancakes braten","Mit Beeren servieren"]}},
    {"id":"mp1-so-d","dayIndex":6,"slot":"dinner","recipe":{"id":"mp1-r3b","title":"Spaghetti Carbonara","description":"Perfektes Sonntagsessen","cookingTimeMinutes":25,"difficulty":"Mittel","servings":4,"ingredients":[{"name":"Spaghetti","amount":"400 g"},{"name":"Guanciale","amount":"200 g"},{"name":"Eier","amount":"4 Stück"},{"name":"Pecorino","amount":"120 g"}],"steps":["Nudeln kochen","Guanciale braten","Ei-Mix","Alles vermengen"]}}
  ]$json1$;

  v_plan2 := $json2$[
    {"id":"mp2-mo-b","dayIndex":0,"slot":"breakfast","recipe":{"id":"mp2-r1","title":"Overnight Oats mit Mango","description":"Cremige Haferflocken über Nacht mit tropischen Früchten","cookingTimeMinutes":5,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Haferflocken","amount":"80 g"},{"name":"Pflanzenmilch","amount":"200 ml"},{"name":"Mango","amount":"1/2 Stück"},{"name":"Chiasamen","amount":"1 EL"},{"name":"Ahornsirup","amount":"1 EL"}],"steps":["Alles mischen","Über Nacht kühlen","Mit Mango servieren"]}},
    {"id":"mp2-mo-l","dayIndex":0,"slot":"lunch","recipe":{"id":"mp2-r2","title":"Buddha Bowl mit Quinoa","description":"Bunte Bowl mit Quinoa, Kichererbsen und Tahini-Dressing","cookingTimeMinutes":25,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Quinoa","amount":"200 g"},{"name":"Kichererbsen","amount":"400 g"},{"name":"Süßkartoffel","amount":"1 Stück"},{"name":"Spinat","amount":"100 g"},{"name":"Tahini","amount":"3 EL"},{"name":"Zitronensaft","amount":"2 EL"},{"name":"Knoblauch","amount":"1 Zehe"}],"steps":["Quinoa kochen","Kichererbsen rösten","Süßkartoffel backen","Bowl zusammenstellen","Dressing anrühren"]}},
    {"id":"mp2-mo-d","dayIndex":0,"slot":"dinner","recipe":{"id":"mp2-r3","title":"Rotes Thai-Curry","description":"Cremiges veganes Curry mit Kokosmilch und Gemüse","cookingTimeMinutes":30,"difficulty":"Einfach","servings":4,"ingredients":[{"name":"Rote Currypaste","amount":"2 EL"},{"name":"Kokosmilch","amount":"400 ml"},{"name":"Tofu","amount":"300 g"},{"name":"Paprika","amount":"2 Stück"},{"name":"Zucchini","amount":"1 Stück"},{"name":"Basmati-Reis","amount":"300 g"},{"name":"Limette","amount":"1 Stück"},{"name":"Koriander","amount":"1 Bund"}],"steps":["Tofu anbraten","Currypaste anschwitzen","Gemüse dazu","Mit Kokosmilch ablöschen","15 Min. köcheln","Mit Reis servieren"]}},
    {"id":"mp2-di-b","dayIndex":1,"slot":"breakfast","recipe":{"id":"mp2-r4","title":"Grüner Smoothie Bowl","description":"Energiereiche Bowl mit Spinat, Banane und Toppings","cookingTimeMinutes":10,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Spinat","amount":"100 g"},{"name":"Bananen","amount":"2 Stück"},{"name":"Pflanzenmilch","amount":"100 ml"},{"name":"Granola","amount":"50 g"},{"name":"Beeren","amount":"100 g"},{"name":"Kokosflocken","amount":"2 EL"}],"steps":["Spinat und Bananen mixen","In Bowl füllen","Mit Toppings belegen"]}},
    {"id":"mp2-di-l","dayIndex":1,"slot":"lunch","recipe":{"id":"mp2-r5","title":"Linsendal","description":"Würziges indisches Linsenmus","cookingTimeMinutes":25,"difficulty":"Einfach","servings":4,"ingredients":[{"name":"Rote Linsen","amount":"250 g"},{"name":"Zwiebeln","amount":"2 Stück"},{"name":"Knoblauch","amount":"3 Zehen"},{"name":"Ingwer","amount":"2 cm"},{"name":"Dosentomaten","amount":"400 g"},{"name":"Garam Masala","amount":"2 TL"},{"name":"Kurkuma","amount":"1 TL"}],"steps":["Zwiebeln anbraten","Gewürze rösten","Linsen und Tomaten dazu","20 Min. köcheln","Pürieren"]}},
    {"id":"mp2-di-d","dayIndex":1,"slot":"dinner","recipe":{"id":"mp2-r6","title":"Vegane Pasta Arrabiata","description":"Scharfe Tomatenpasta ohne tierische Produkte","cookingTimeMinutes":20,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Penne","amount":"300 g"},{"name":"Dosentomaten","amount":"400 g"},{"name":"Knoblauch","amount":"4 Zehen"},{"name":"Chili","amount":"2 Stück"},{"name":"Olivenöl","amount":"4 EL"},{"name":"Petersilie","amount":"1 Bund"}],"steps":["Knoblauch und Chili anbraten","Tomaten dazu","10 Min. köcheln","Mit Pasta mischen"]}},
    {"id":"mp2-mi-b","dayIndex":2,"slot":"breakfast","recipe":{"id":"mp2-r1b","title":"Overnight Oats","description":"Einfaches Frühstück","cookingTimeMinutes":5,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Haferflocken","amount":"80 g"},{"name":"Pflanzenmilch","amount":"200 ml"},{"name":"Obst","amount":"nach Wahl"}],"steps":["Mischen","Kühlen","Genießen"]}},
    {"id":"mp2-mi-d","dayIndex":2,"slot":"dinner","recipe":{"id":"mp2-r7","title":"Vegane Burger","description":"Saftige Patties aus schwarzen Bohnen","cookingTimeMinutes":30,"difficulty":"Mittel","servings":4,"ingredients":[{"name":"Schwarze Bohnen","amount":"400 g"},{"name":"Haferflocken","amount":"80 g"},{"name":"Paprikapulver","amount":"2 TL"},{"name":"Knoblauch","amount":"2 Zehen"},{"name":"Burger-Buns","amount":"4 Stück"},{"name":"Salat","amount":"4 Blätter"},{"name":"Tomaten","amount":"2 Stück"}],"steps":["Bohnen zerdrücken","Mit Haferflocken formen","Braten","Im Bun anrichten"]}},
    {"id":"mp2-do-l","dayIndex":3,"slot":"lunch","recipe":{"id":"mp2-r2b","title":"Buddha Bowl","description":"Bunte vegane Bowl","cookingTimeMinutes":20,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Quinoa","amount":"200 g"},{"name":"Kichererbsen","amount":"200 g"},{"name":"Gemüse","amount":"nach Wahl"}],"steps":["Kochen","Zusammenstellen","Dressing dazu"]}},
    {"id":"mp2-do-d","dayIndex":3,"slot":"dinner","recipe":{"id":"mp2-r8","title":"Vegane Gemüsepfanne","description":"Schnelle Wokpfanne mit Tofu und saisonalem Gemüse","cookingTimeMinutes":20,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Tofu","amount":"300 g"},{"name":"Brokkoli","amount":"200 g"},{"name":"Karotten","amount":"2 Stück"},{"name":"Paprika","amount":"1 Stück"},{"name":"Sojasoße","amount":"3 EL"},{"name":"Ingwer","amount":"1 cm"},{"name":"Sesam","amount":"1 EL"}],"steps":["Tofu anbraten","Gemüse dazu","Mit Sojasoße würzen","Mit Reis servieren"]}},
    {"id":"mp2-fr-b","dayIndex":4,"slot":"breakfast","recipe":{"id":"mp2-r4b","title":"Smoothie Bowl","description":"Grüne Power-Bowl","cookingTimeMinutes":10,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Banane","amount":"2 Stück"},{"name":"Spinat","amount":"50 g"},{"name":"Toppings","amount":"nach Wahl"}],"steps":["Mixen","Belegen"]}},
    {"id":"mp2-fr-d","dayIndex":4,"slot":"dinner","recipe":{"id":"mp2-r3b","title":"Thai-Curry","description":"Veganes Curry","cookingTimeMinutes":30,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Kokosmilch","amount":"400 ml"},{"name":"Currypaste","amount":"2 EL"},{"name":"Gemüse","amount":"nach Wahl"}],"steps":["Anbraten","Köcheln","Servieren"]}},
    {"id":"mp2-sa-b","dayIndex":5,"slot":"breakfast","recipe":{"id":"mp2-r9","title":"Vegane Pancakes","description":"Fluffige Pancakes ohne Ei","cookingTimeMinutes":20,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Mehl","amount":"150 g"},{"name":"Pflanzenmilch","amount":"200 ml"},{"name":"Backpulver","amount":"2 TL"},{"name":"Leinsamen","amount":"1 EL"},{"name":"Agavendicksaft","amount":"2 EL"}],"steps":["Teig mischen","Pancakes braten","Mit Früchten servieren"]}},
    {"id":"mp2-sa-d","dayIndex":5,"slot":"dinner","recipe":{"id":"mp2-r5b","title":"Linsendal","description":"Indisches Linsenmus","cookingTimeMinutes":25,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Linsen","amount":"200 g"},{"name":"Gewürze","amount":"nach Wahl"}],"steps":["Kochen","Würzen"]}},
    {"id":"mp2-so-b","dayIndex":6,"slot":"breakfast","recipe":{"id":"mp2-r1c","title":"Overnight Oats","description":"Wochenendfrühstück","cookingTimeMinutes":5,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Haferflocken","amount":"160 g"},{"name":"Pflanzenmilch","amount":"400 ml"},{"name":"Früchte","amount":"nach Wahl"}],"steps":["Vorbereiten","Kühlen","Genießen"]}},
    {"id":"mp2-so-d","dayIndex":6,"slot":"dinner","recipe":{"id":"mp2-r7b","title":"Vegane Burger","description":"Perfekter Wochenendburger","cookingTimeMinutes":30,"difficulty":"Mittel","servings":4,"ingredients":[{"name":"Bohnenpattys","amount":"4 Stück"},{"name":"Buns","amount":"4 Stück"},{"name":"Toppings","amount":"nach Wahl"}],"steps":["Braten","Anrichten"]}}
  ]$json2$;

  v_plan3 := $json3$[
    {"id":"mp3-mo-b","dayIndex":0,"slot":"breakfast","recipe":{"id":"mp3-r1","title":"Protein-Overnight-Oats","description":"Eiweißreiche Haferflocken für den aktiven Start","cookingTimeMinutes":5,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Haferflocken","amount":"60 g"},{"name":"Proteinpulver","amount":"1 Schaufel"},{"name":"Mandelmilch","amount":"200 ml"},{"name":"Banane","amount":"1/2 Stück"},{"name":"Erdnussbutter","amount":"1 EL"}],"steps":["Alle Zutaten mischen","Über Nacht kühlen","Morgens genießen"]}},
    {"id":"mp3-mo-l","dayIndex":0,"slot":"lunch","recipe":{"id":"mp3-r2","title":"Hähnchen-Quinoa-Bowl","description":"Proteinreiche Bowl für den Mittag","cookingTimeMinutes":30,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Hähnchenbrust","amount":"300 g"},{"name":"Quinoa","amount":"200 g"},{"name":"Brokkoli","amount":"200 g"},{"name":"Karotten","amount":"2 Stück"},{"name":"Sesam","amount":"1 EL"},{"name":"Sojasoße","amount":"2 EL"}],"steps":["Quinoa kochen","Hähnchen grillen","Gemüse dämpfen","Bowl zusammenstellen"]}},
    {"id":"mp3-mo-d","dayIndex":0,"slot":"dinner","recipe":{"id":"mp3-r3","title":"Süßkartoffel-Chili","description":"Würziges Chili mit Süßkartoffeln und Bohnen","cookingTimeMinutes":35,"difficulty":"Einfach","servings":4,"ingredients":[{"name":"Süßkartoffeln","amount":"400 g"},{"name":"Rote Bohnen","amount":"400 g"},{"name":"Dosentomaten","amount":"400 g"},{"name":"Zwiebeln","amount":"2 Stück"},{"name":"Knoblauch","amount":"3 Zehen"},{"name":"Chili-Pulver","amount":"2 TL"},{"name":"Kreuzkümmel","amount":"1 TL"}],"steps":["Süßkartoffeln würfeln","Anbraten","Alle Zutaten dazu","25 Min. köcheln"]}},
    {"id":"mp3-di-b","dayIndex":1,"slot":"breakfast","recipe":{"id":"mp3-r1b","title":"Protein-Oats","description":"Eiweißreich für den Start","cookingTimeMinutes":5,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Haferflocken","amount":"60 g"},{"name":"Proteinpulver","amount":"1 Schaufel"},{"name":"Milch","amount":"200 ml"}],"steps":["Mischen","Kühlen"]}},
    {"id":"mp3-di-l","dayIndex":1,"slot":"lunch","recipe":{"id":"mp3-r2b","title":"Hähnchen-Bowl","description":"Proteinreiche Mittagsmahlzeit","cookingTimeMinutes":15,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Hähnchen vorgegart","amount":"150 g"},{"name":"Quinoa","amount":"100 g"},{"name":"Gemüse","amount":"nach Wahl"}],"steps":["Alles aufwärmen","In Bowl anrichten"]}},
    {"id":"mp3-di-d","dayIndex":1,"slot":"dinner","recipe":{"id":"mp3-r4","title":"Lachs Teriyaki","description":"Glasierter Lachs mit Teriyaki-Sauce und Edamame","cookingTimeMinutes":25,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Lachsfilets","amount":"2 Filets"},{"name":"Teriyaki-Sauce","amount":"4 EL"},{"name":"Edamame","amount":"150 g"},{"name":"Jasmin-Reis","amount":"200 g"},{"name":"Sesam","amount":"1 TL"},{"name":"Frühlingszwiebeln","amount":"2 Stück"}],"steps":["Reis kochen","Lachs mit Teriyaki marinieren","Braten","Mit Edamame servieren"]}},
    {"id":"mp3-mi-b","dayIndex":2,"slot":"breakfast","recipe":{"id":"mp3-r5","title":"Egg-Muffins","description":"Eiweißreiche Ei-Muffins zum Vorkochen","cookingTimeMinutes":20,"difficulty":"Einfach","servings":6,"ingredients":[{"name":"Eier","amount":"6 Stück"},{"name":"Paprika","amount":"1 Stück"},{"name":"Spinat","amount":"50 g"},{"name":"Feta","amount":"50 g"},{"name":"Salz und Pfeffer","amount":"nach Geschmack"}],"steps":["Ofen auf 180 Grad","Eier aufschlagen","Gemüse dazu","In Muffinform","15 Min. backen"]}},
    {"id":"mp3-mi-l","dayIndex":2,"slot":"lunch","recipe":{"id":"mp3-r3b","title":"Süßkartoffel-Chili","description":"Aufgewärmtes Chili","cookingTimeMinutes":5,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Chili vorgegart","amount":"1 Portion"}],"steps":["Aufwärmen","Genießen"]}},
    {"id":"mp3-mi-d","dayIndex":2,"slot":"dinner","recipe":{"id":"mp3-r6","title":"Hähnchen-Wrap","description":"Würziger Wrap mit Joghurt-Sauce","cookingTimeMinutes":20,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Hähnchenbrust","amount":"300 g"},{"name":"Tortilla-Wraps","amount":"4 Stück"},{"name":"Joghurt","amount":"150 ml"},{"name":"Gurke","amount":"1/2 Stück"},{"name":"Salat","amount":"50 g"},{"name":"Zaatar","amount":"1 TL"}],"steps":["Hähnchen würzen und braten","Joghurt mit Gurke mischen","In Wraps füllen"]}},
    {"id":"mp3-do-b","dayIndex":3,"slot":"breakfast","recipe":{"id":"mp3-r5b","title":"Egg-Muffins","description":"Vorgebackene Muffins","cookingTimeMinutes":2,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Egg-Muffins vorgebacken","amount":"3 Stück"}],"steps":["Aufwärmen"]}},
    {"id":"mp3-do-l","dayIndex":3,"slot":"lunch","recipe":{"id":"mp3-r7","title":"Thunfisch-Salat","description":"Leichter Salat für die Mittagspause","cookingTimeMinutes":10,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Thunfisch Dose","amount":"1 Dose"},{"name":"Mischsalat","amount":"100 g"},{"name":"Kirschtomaten","amount":"10 Stück"},{"name":"Olivenöl","amount":"2 EL"},{"name":"Zitronensaft","amount":"1 EL"}],"steps":["Thunfisch abtropfen","Mit Salat mischen","Würzen"]}},
    {"id":"mp3-do-d","dayIndex":3,"slot":"dinner","recipe":{"id":"mp3-r4b","title":"Lachs Teriyaki","description":"Einfaches Abendessen","cookingTimeMinutes":20,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Lachs","amount":"160 g"},{"name":"Teriyaki-Sauce","amount":"2 EL"},{"name":"Reis","amount":"100 g"}],"steps":["Kochen","Servieren"]}},
    {"id":"mp3-fr-b","dayIndex":4,"slot":"breakfast","recipe":{"id":"mp3-r1c","title":"Protein-Oats","description":"Freitagsfrühstück","cookingTimeMinutes":5,"difficulty":"Einfach","servings":1,"ingredients":[{"name":"Haferflocken","amount":"60 g"},{"name":"Proteinpulver","amount":"1 Schaufel"}],"steps":["Mischen"]}},
    {"id":"mp3-fr-d","dayIndex":4,"slot":"dinner","recipe":{"id":"mp3-r8","title":"Linsen-Suppe","description":"Grosse Portion Linsensuppe zum Vorbereiten","cookingTimeMinutes":30,"difficulty":"Einfach","servings":6,"ingredients":[{"name":"Rote Linsen","amount":"400 g"},{"name":"Möhren","amount":"3 Stück"},{"name":"Paprika","amount":"2 Stück"},{"name":"Gemüsebrühe","amount":"1.5 Liter"},{"name":"Kreuzkümmel","amount":"2 TL"},{"name":"Paprikapulver","amount":"1 TL"}],"steps":["Gemüse schneiden","Anbraten","Linsen und Brühe dazu","25 Min. kochen","Pürieren"]}},
    {"id":"mp3-sa-b","dayIndex":5,"slot":"breakfast","recipe":{"id":"mp3-r9","title":"Protein-Pancakes","description":"Wochenend-Pancakes mit Protein","cookingTimeMinutes":20,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Haferflocken","amount":"100 g"},{"name":"Quark","amount":"200 g"},{"name":"Eier","amount":"2 Stück"},{"name":"Backpulver","amount":"1 TL"},{"name":"Beeren","amount":"100 g"}],"steps":["Alles mixen","Braten","Mit Beeren servieren"]}},
    {"id":"mp3-sa-d","dayIndex":5,"slot":"dinner","recipe":{"id":"mp3-r10","title":"Beef Stir-Fry","description":"Schnelles Wokgericht mit Rindfleisch","cookingTimeMinutes":20,"difficulty":"Mittel","servings":2,"ingredients":[{"name":"Rinderstreifen","amount":"300 g"},{"name":"Brokkoli","amount":"200 g"},{"name":"Paprika","amount":"2 Stück"},{"name":"Knoblauch","amount":"2 Zehen"},{"name":"Ingwer","amount":"1 cm"},{"name":"Austernsoße","amount":"2 EL"},{"name":"Sojasoße","amount":"2 EL"}],"steps":["Fleisch scharf anbraten","Gemüse dazu","Mit Soßen würzen","Mit Reis servieren"]}},
    {"id":"mp3-so-b","dayIndex":6,"slot":"breakfast","recipe":{"id":"mp3-r11","title":"Avocado Toast Deluxe","description":"Sonntagsfrühstück mit allem Drum und Dran","cookingTimeMinutes":15,"difficulty":"Einfach","servings":2,"ingredients":[{"name":"Sauerteigbrot","amount":"4 Scheiben"},{"name":"Avocado","amount":"2 Stück"},{"name":"Eier","amount":"4 Stück"},{"name":"Lachsschinken","amount":"100 g"},{"name":"Kräuter","amount":"nach Wahl"}],"steps":["Toast rösten","Avocado würzen","Eier pochieren","Anrichten"]}},
    {"id":"mp3-so-d","dayIndex":6,"slot":"dinner","recipe":{"id":"mp3-r6b","title":"Hähnchen-Wrap","description":"Leckerer Wrap für das Wochenende","cookingTimeMinutes":20,"difficulty":"Einfach","servings":4,"ingredients":[{"name":"Hähnchen","amount":"500 g"},{"name":"Wraps","amount":"8 Stück"},{"name":"Salat","amount":"100 g"},{"name":"Tomaten","amount":"2 Stück"}],"steps":["Hähnchen braten","In Wraps anrichten"]}}
  ]$json3$;

  -- ──────────────────────────────────────────────────────────
  -- PLAN 1 einfügen
  -- ──────────────────────────────────────────────────────────
  INSERT INTO public.community_meal_plans (
    user_id, author_name, title, description, tags, plan_json, is_published, view_count
  ) VALUES (
    v_user1, 'Marco Küchenchef',
    'Mediterrane Genusswoche 🌊',
    'Eine Woche voller Mittelmeer-Aromen. Leicht, frisch und einfach zuzubereiten.',
    ARRAY['Mediterran','Leicht','Sommer','Gesund'],
    v_plan1, true, 145
  ) ON CONFLICT (id) DO NOTHING;

  -- ──────────────────────────────────────────────────────────
  -- PLAN 2 einfügen
  -- ──────────────────────────────────────────────────────────
  INSERT INTO public.community_meal_plans (
    user_id, author_name, title, description, tags, plan_json, is_published, view_count
  ) VALUES (
    v_user2, 'Lena Grünzeug',
    'Vegane Power-Woche 🌱',
    'Beweise dass pflanzliche Küche alles andere als langweilig ist. Sättigend, lecker und nährstoffreich.',
    ARRAY['Vegan','Vegetarisch','Gesund','Protein','Meal-Prep'],
    v_plan2, true, 203
  ) ON CONFLICT (id) DO NOTHING;

  -- ──────────────────────────────────────────────────────────
  -- PLAN 3 einfügen
  -- ──────────────────────────────────────────────────────────
  INSERT INTO public.community_meal_plans (
    user_id, author_name, title, description, tags, plan_json, is_published, view_count
  ) VALUES (
    v_user3, 'Sara FitFood',
    'Meal-Prep Woche für Berufstätige ⚡',
    'Alle Mahlzeiten in 2h am Sonntag vorbereiten und entspannt durch die Woche kommen.',
    ARRAY['Meal-Prep','Schnell','Fitness','Protein','Gesund'],
    v_plan3, true, 178
  ) ON CONFLICT (id) DO NOTHING;

  RAISE NOTICE '✅ 3 Community-Wochenpläne mit echten Rezepten erfolgreich angelegt!';
END $outer$;
